### ISSUE TITLE
SRS: Potential System Contexts

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#11]
Can you be more explicit about the interface dependencies between your system and external ones? From what I can see, there is a dependency between the parent program/user and the generator, and the parent program/user and the generated code. Does this mean that the parent program/user does not directly interact with the generator to get its outputs? It can just pick it up from somewhere else (the generator does not send it back to the calling program/the calling program does not request it from the generator)?

A much smaller issue - can you write some sort of lead in for the responsibility lists (an "in general" description of what the user and program responsibilities are)? Right now, they just appear with no warning as if they were added as an afterthought.

**Comment by aschaap** [comment]
I've clarified that the generator needs to be called by the parent program as well.  I've added a sentence introducing the responsibilities.

**Comment by GenevaS** [comment]
Still not clear on how exactly the parent program and the generator interact. Is the generator included in the parent program with a library reference or call?

**Comment by aschaap** [comment]
Either one would work, but I've added an explicit mention of including a library. Ultimately, the function provided by the generator will have to be called.
