### ISSUE TITLE
SRS: Potential User Characteristics and Potential System Constraints

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#12]
If I understand correctly, this software already exists and the documentation is being written retroactively. While the software was being built, was there a specific reason why OCaml was chosen for the implementation language? If there is not, I think that this is a design decision and belongs in a future document. 

As with issues #9 (User Characteristics) and (again) some of Issue #7 (Purpose of the Document), can you be more specific about the type of expected knowledge that the intended users need? What should the "other programs" support? What kind of knowledge do the programmers need to write these other programs?

**Comment by aschaap** [comment]
MetaOCaml is fairly unique (to the best of my knowledge) in terms of the guarantees it provides about the code it produces. I've added more about this to the document.

I've tried to be more specific about what knowledge the intended user needs.

**Comment by GenevaS** [comment]
Style related: you have a whole sentence enclosed in brackets in the Potential User Characteristics section. I don't think that they add anything, and the comment should stand-alone as a sentence in the paragraph.

**Comment by aschaap** [comment]
You're right, I've removed them.
