### ISSUE TITLE
SRS: Definition of Step Size (Very minor)

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#14]
Can you rewrite the definition of step size so that is does not explicitly refer to RK methods and exchange it for a more robust definition (e.g. the distance between points in what? For what?)? I think this can be made much clearer.

**Comment by aschaap** [comment]
I've pushed an attempt at clarification.

**Comment by GenevaS** [comment]
Ah, sorry. I meant in the terminology list of definitions. This explanation is much better though, so I think you can just move it up and call it a day.

**Comment by aschaap** [comment]
That makes sense - I've moved most of the definition.

**Comment by GenevaS** [comment]
I don't think you pushed that update - I don't see any changes :/

**Comment by aschaap** [comment]
Indeed, thank you for reminding me!

**Comment by GenevaS** [comment]
Ok, everything looks good here where step size is concerned. On to the next one?
