### ISSUE TITLE
SRS: Data Definitions (General)

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#16]
I would ask Dr. Smith about this one first:

Shouldn't the equations be written such that the symbol being defined is the LHS and the equation that it can be found with is the RHS?

A trivial example: instead of writing `x(t0) = x0` for Initial values (`x0`), write `x0 = x(t0)`.

**Comment by aschaap** [comment]
I agree. However, in the case of this example, `x0` is provided and `x(t0)` is what one wants know.

**Comment by GenevaS** [comment]
Shouldn't your symbol for this definition be ``x(t0)`` then? If I take the same original example, you state that the symbol is ``x0`` but then define the equation as ``x(t0) = x0``. My confusion is in what you are calling your "symbol" for the definition.

**Comment by aschaap** [comment]
Good question. I wrote it up the way most sources seem to - I think that's because `x(t0)` could hypothetically be assigned different `x0`'s, since we only know `x'`, and not `x`. (Intuitively, since we often need to add a + C when integrating, there could be multiple solutions for different values of C.)

**Comment by aschaap** [comment]
@smiths, what do you think the right thing to do is in this case?

**Comment by smiths** [comment]
I'm not sure what the question is here.  If LHS = RHS, then RHS = LHS.  The symbols are x, t0 and x0.  x has type real to real, t0 is real and x0 is real.  Stylistically, I prefer x(t0) = x0, but it isn't a strong preference.

**Comment by aschaap** [comment]
I've left it as is as this seems more a matter of personal taste.

**Comment by GenevaS** [comment]
Ok, fair enough.
