### ISSUE TITLE
SRS: Goal Statements

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#17]
I think you should lift the input requirements (initial value, interval, etc.) out of your goal statement and into the "Given the non-stiff ODE" part of this section (i.e. list all of the inputs in the same spot).

Additionally: What is a "spline"? "Type-safe"? These should be added to your definitions section.

**Comment by aschaap** [comment]
Makes sense, I've moved it. I've removed references to splines other than that they will be implemented later. I've added type-safe to the definitions list.

**Comment by GenevaS** [comment]
I think that if you have to say "Given" in your goal statement, it should be listed with the other inputs.

**Comment by aschaap** [comment]
Indeed, I guess I missed that one. I've moved it as well.
