### ISSUE TITLE
SRS: Definitions and Terminology (Very minor)

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#19]
Could you alphabetize the list please? It would make it easier to look up terms.

**Comment by aschaap** [comment]
I had ordered them in a way that one could read them top to bottom, but you're probably right in that people want to look individual ones up as they read.

**Comment by GenevaS** [comment]
Looking good :) I would swap the order of IVP and initial values then regenerate the PDF to wrap up this issue.

**Comment by aschaap** [comment]
I don't mind, but I thought space came before s (or ignoring the space, the p of IVP). How do you see it?

**Comment by GenevaS** [comment]
Shorter words are listed first in dictionaries (or at least my dictionary), so I always default to that.

**Comment by aschaap** [comment]
Swapped!

**Comment by GenevaS** [comment]
Nice.
