### ISSUE TITLE
Modifying CA template: changing "SI Units"

### ISSUE THREAD

**Issue by aschaap** [aschaap/cas741#2]
Hello Dr. Smith,

For solving ODE's, there aren't really any units to be used for the inputs. I've taken the liberty of replacing "SI Units" with "Units" (which was previously commented out) to denote that inputs belonged to e.g. real or complex number sets. I could change that to "Types" if preferred. What are your thoughts on this change?

The current document can be viewed at: https://github.com/aschaap/cas741/blob/master/Doc/SRS/CA.pdf

Thank you!

**Comment by smiths** [comment]
Real and complex numbers are not units.  I think you are better off with just stating in the section that units are not applicable for this problem, as discussed in #3.

If you only have real and complex numbers, you probably do not need a table of types, but if there are other types in your CA, yes, a table of types would make sense.
