### ISSUE TITLE
SRS: Variabilities Preamble (Very minor)

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#20]
As it is written, the listing of subsections does not follow how they actually appear (i.e. you state that the instance models are followed by assumptions, etc., but assumptions come first in the document.). 

In your case, aren't your Instance Models the same as your Calculations? You use both in this preamble and treat them as separate sections.

**Comment by aschaap** [comment]
Yes, they are. initially I had a separate instance models section, but I changed this due to Dr. Smith's answer to #5.

**Comment by GenevaS** [comment]
I have a follow-up question. What do you mean when you write "After instance models, output is covered."? What does "output" refer to here?

**Comment by aschaap** [comment]
Since Output is under Variabilities, I assumed it covered potential variabilities in output. I've tried to clarify that.

**Comment by GenevaS** [comment]
I am honestly not sure what "Output" means here either. I thought it was similar to the "Properties of a Correct Solution" from the SRS template. I think we should ask...

**Comment by aschaap** [comment]
Alright - @smiths, could you clarify what "Output" under Variabilities in a commonality analysis is expected to contain?

**Comment by smiths** [comment]
@aschapp, your interpretation (as written above) is correct.  The "Output" heading is for variabilities in the output.  This is discussed in the Smith2006 reference.

@GenevaS, a section with "properties of a correct solution" would be a nice addition to the CA, where appropriate, but it isn't part of the starting template.  I'll think about adding it in the future though.  (The challenge is that the properties must be correct for all family members, or the properties should be tied to variabilities.)

**Comment by GenevaS** [comment]
Thank you for clarifying. So if I am reading your Output section correctly, your family will always produce a function of the same form no matter which member is used?

**Comment by aschaap** [comment]
Yes, different members should produce the same kind of solution, all that should vary there is accuracy.

**Comment by GenevaS** [comment]
Perhaps mention that? "The accuracy of the generated function depends on the family member that produced it." <- Something like this? (And I think this also means that you should remove N/A since there is content here now.)

**Comment by aschaap** [comment]
The N/A denoted a lack of variability, but I guess it was confusing. I've removed it and tried to be more specific about the output.

**Comment by GenevaS** [comment]
Much clearer (to me anyways).
