### ISSUE TITLE
SRS: Instance Models

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#22]
Some more smaller points to deal with:

- You introduce some new notations here (**k**, **Y**) that should be added to your Table of Symbols.
- This could be my unfamiliarity with RK methods, but doesn't second order come before fourth order? Can you swap the table order to reflect this please?
- Most of the side notes you have in brackets () could be incorporated into the body text with some rewriting, and I think it would help with readability.

**Comment by aschaap** [comment]
- They're there, but I guess the connection wasn't obvious as I wrote them too compact to be unambiguous
- They're independent, but I've swapped them regardless
- I moved this to the description and tweaked it a bit
