### ISSUE TITLE
SRS: Output

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#23]
I already touched on this in Issue #21 (Assumptions) - isn't there some property of a correct solution that you could include here? Are there bounds that can be checked? Any kind of post-processing code inspection that can be automated?

**Comment by aschaap** [comment]
There's not that much that I can say other than the type of the function, since everything depends on the given ODE. Nevertheless, I tried to be more specific.

**Comment by GenevaS** [comment]
:)
