### ISSUE TITLE
SRS: No requirements or likely changes?

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#24]
I don't know if the template was correct in the exclusion of the requirements or likely changes sections. Double check with Dr. Smith?

**Comment by aschaap** [comment]
As far as I understood this was the intent of a commonality analysis. If you remember the slides, the CA sits above multiple SRSes.

**Comment by GenevaS** [comment]
I think you are correct. I found an issue on the GitLab that Dr. Smith answered for this exact question.
