### ISSUE TITLE
Modifying the CA template: Removing the "Table of Units"

### ISSUE THREAD

**Issue by aschaap** [aschaap/cas741#3]
related to the previous issue, but in a different place; since there are no units involved in the problem of solving ODEs (as far as I understand), I have no use for the heading that announces a table of units. I saw Paul (@aoananp) addressed this by saying it is not applicable. Would you prefer this because it signifies that some thought has been put into it rather than potentially having been omitted?

The current state of the document is reflected here: https://github.com/aschaap/cas741/blob/master/Doc/SRS/CA.pdf

Thank you!

**Comment by smiths** [comment]
You should still include the section title and just say that units are not applicable.  If you leave the title out a reader doesn't know whether you left it out on purpose, or forgot.
