### ISSUE TITLE
Not Like A MG

### ISSUE THREAD

**Issue by halonazhao** [aschaap/cas741#32]
If you don't decompose your project into modules, I don't think you have to use the MG templete at all. Because there are too many things that do not make sense in your document like the introduction section, module decomposition section and etc. I have no ideas how to fit this to MG.

**Comment by aschaap** [comment]
That is correct. As Dr. Smith pointed out, this document is a combination of MG and MIS, and while I reuse parts of the templates, the structure will ultimately be different. I've renamed it to `Design' as requested by Dr. Smith in issue #36 to avoid confusion.
