### ISSUE TITLE
MIS - Comments (Combined into one)

### ISSUE THREAD

**Issue by aoananp** [aschaap/cas741#38]
Alex,

I really like the way you presented your MIS.
Due to the fact that the format is a departure from the standard MIS format that was presented in class and the way your software is structured, it makes sense to write it this way.
I can't find anything else to comment on as it is an unusual write-up.

I do have one comment - I perused the document and I saw the "local functions" generated.
I'm not sure if I understood it correctly, but does it mean that the software will only have one exposed access program to the user called "odesolve"?
And that the local functions are the ones generated by it?
You could've provided a high level description and expectations of each local function created as part of the MIS - maybe their behaviour as well to provide some sort of guidance to the reviewer and maintainer of the code.

Otherwise, the document looks good. Dr. Smith has made some good comments.

There is also a typo you can look into with the Section showing as ??:
https://github.com/aschaap/cas741/blob/9040fd8b56a6fe960ee7787e36e6c2124a308b6d/Doc/Design/Design.tex#L188

Cheers,
Paul

**Comment by aschaap** [comment]
Hi Paul,

Thank you, this is very encouraging. Good point - yes, only odesolve is available to the user/driver program. Local functions are written by the programmer, and assist in generating the resulting code. I guess I should clarify this. Yes, I agree that more information for each local function would be good - as it is it is cryptic to the reader. I guess I was conservative in modifying that part of the template I incorporated. Thank you for catching that silly mistake with the \ref, I've pushed a fix.

**Comment by aschaap** [comment]
I've tried to clarify the things you pointed out, especially the "Local Functions" part. Hopefully it makes more sense to new readers now. Feel free to let me know if this is the case for you, but if you're too busy I'll probably close this issue in a few days.
