### ISSUE TITLE
Should I use the Calculation subheading of Variabilities for Instance Models?

### ISSUE THREAD

**Issue by aschaap** [aschaap/cas741#5]
Hi Dr. Smith,

It just occurred to me that one could interpret the Calculation heading to contain variabilities in terms of calculations performed between different family members. In my case, RK2 vs RK4 would seem different enough. Would this be abusing the Calculation heading? 

Thank you in advance!

**Comment by smiths** [comment]
Yes, the calculation heading would contain variabilities related to calculation, which in your case is different algorithm choices.   Yes, RK2 and RK4 are definitely different enough.
