### ISSUE TITLE
SRS: Table of Symbols Preamble

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#6]
This is a minor issue, but the preamble to the Table of Symbols states that the symbols were selected to represent heat transfer literature and solar water heating systems. This should be updated to reflect Runge-Kutta instead.

Another small side issue - I don't know how Dr. Smith feels about this (I would check with him before making this change), but if your document reflects unitless models, I don't think that your table needs to have a column for units.

**Comment by aschaap** [comment]
I addressed the first half and alphabetized the symbols.

@smiths, I agree with Geneva - since I already state that I don't use any physical units throughout the document, a unit column containing N/A for every entry seems redundant. What do you think?

Thank you in advance!

**Comment by smiths** [comment]
@GenevaS and @aschaap, I agree that a unit column where all entries are N/A is redundant.  As long as you state that you do not have physical units for any of the variables, you can remove units from further reference.

**Comment by aschaap** [comment]
Thank you @smiths, I've removed the units column and updated the text above the table to reflect this change.

**Comment by GenevaS** [comment]
Ok, just regenerate your PDF and I will be satisfied :)

**Comment by aschaap** [comment]
The PDF has since been regenerated by @smiths when adding comments, I will assume satisfaction has been achieved :)

**Comment by GenevaS** [comment]
Yup.
