### ISSUE TITLE
SRS: Purpose of the Document (Content)

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#7]
As presented, there is very little useful information in this section. The purpose has been stated, but the question of _why_ this document exists is unclear (is it for maintenance? Is it the user guide?).

There is also no mention of who the intended audience of this document is. Is it for the person using the software? For someone who wants to expand or refine it? These are the same people that you describe in the User Characteristics section, but you need to be explicit about who they are and why they are using your software.

**Comment by aschaap** [comment]
Agreed, I've tried to rectify this.

**Comment by GenevaS** [comment]
I think adding an explicit section reference to the "Characteristics of the Intended Reader" should be added. After that, I think that this issue can be closed.

**Comment by aschaap** [comment]
I've added a reference.
