### ISSUE TITLE
SRS: Characteristics of the Intended User

### ISSUE THREAD

**Issue by GenevaS** [aschaap/cas741#9]
This description of the user is pretty vague. What kind of calculus? Programming courses (just functional)? The group of people with some understanding of undergraduate STEM is very broad...is someone from chemistry an intended reader?

Some of this ties into Issue #7 (Purpose of the Document).

**Comment by aschaap** [comment]
Chemistry would be fine, as long as they have the math background. I've tried to be more specific.

**Comment by GenevaS** [comment]
I think it is fine to state that they need an undergraduate understanding of something and a higher level understanding of something else. No need to state that they might be mutually exclusive.

**Comment by aschaap** [comment]
I've tried to clarify this.
